### ISSUE TITLE
Feature Request - Add VPC networking and security. 

### ISSUE THREAD

**Issue by christopinka** [devopsgoat/terraform-aws-transfer#10]
Feature Request - Add VPC networking and security. Thanks!

**Comment by christopinka** [comment]
https://aws.amazon.com/about-aws/whats-new/2020/01/aws-transfer-for-sftp-supports-vpc-security-groups-and-elastic-ip-addresses/#:~:text=AWS%20Transfer%20for%20SFTP%20supports%20VPC%20Security%20Groups%20and%20Elastic%20IP%20addresses,-Posted%20On%3A%20Jan&text=AWS%20Transfer%20for%20SFTP%20(AWS,security%20to%20their%20SFTP%20servers.

**Comment by darren-reddick** [comment]
Hi,
I hadnt looked at that new security feature yet. This module is about building the custom IdP for the transfer service. The infrastructure (server, networking etc) itself is provisioned by the AWS Provider https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server.

If that doesnt have the capability yet I would raise a feature request there.

Thanks
